-- 코드를 입력하세요
SELECT R.NAME, R.DATETIME
FROM 
(SELECT I.DATETIME, I.NAME FROM ANIMAL_INS I, ANIMAL_OUTS O
 WHERE I.ANIMAL_ID = O.ANIMAL_ID(+)
 AND O.ANIMAL_ID IS NULL 
 ORDER BY I.DATETIME) R
WHERE ROWNUM <= 3;