-- 코드를 입력하세요
SELECT JOIN.FLAVOR
FROM 
    (SELECT J.FLAVOR 
     FROM FIRST_HALF F, JULY J
    WHERE J.FLAVOR = F.FLAVOR
    GROUP BY J.FLAVOR
    ORDER BY SUM(J.TOTAL_ORDER + F.TOTAL_ORDER) DESC) JOIN
WHERE ROWNUM <= 3;